# Deviations from normality

In [72]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import edhec_risk_kit as erk

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [22]:
hfi = erk.get_hfi_returns()

In [24]:
hfi.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275

In [26]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean()>hfi.median()], axis="columns")

0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

In [32]:
erk.skewness(hfi).sort_values()

Fixed Income Arbitrage   -3.940320
Convertible Arbitrage    -2.639592
Equity Market Neutral    -2.124435
Relative Value           -1.815470
Event Driven             -1.409154
Merger Arbitrage         -1.320083
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Long/Short Equity        -0.390227
Funds Of Funds           -0.361783
CTA Global                0.173699
Short Selling             0.767975
Global Macro              0.982922
dtype: float64

# Skewness

In [34]:
!pip install scipy

     |████████████████████████████████| 25.2MB 6.3MB/s eta 0:00:01


In [35]:
import scipy.stats

In [41]:
scipy.stats.skew(hfi)

array([-2.63959223,  0.17369864, -1.30084204, -1.16706749, -2.12443538,
       -1.40915356, -3.94032029,  0.98292188, -0.39022677, -1.32008333,
       -1.81546975,  0.76797484, -0.36178308])

In [42]:
import numpy as np

In [54]:
normal_rets = np.random.normal(0, .15, size=(hfi.shape[0],1))

In [55]:
erk.skewness(normal_rets)

0.1337968797913296

# Kurtosis

In [60]:
# Random numbers are close to kurtosis value of 3 as should be
erk.kurtosis(normal_rets)

2.7224962231724508

In [63]:
# Scipy gives you the excess kurtosis
scipy.stats.kurtosis(normal_rets)

array([-0.27750378])

In [61]:
erk.kurtosis(hfi)

Convertible Arbitrage     23.280834
CTA Global                 2.952960
Distressed Securities      7.889983
Emerging Markets           9.250788
Equity Market Neutral     17.218555
Event Driven               8.035828
Fixed Income Arbitrage    29.842199
Global Macro               5.741679
Long/Short Equity          4.523893
Merger Arbitrage           8.738950
Relative Value            12.121208
Short Selling              6.117772
Funds Of Funds             7.070153
dtype: float64

In [64]:
scipy.stats.kurtosis(hfi)

array([20.28083446, -0.04703963,  4.88998336,  6.25078841, 14.21855526,
        5.03582817, 26.84219928,  2.74167945,  1.52389258,  5.73894979,
        9.12120787,  3.11777175,  4.07015278])

In [65]:
scipy.stats.jarque_bera(normal_rets)

(1.6285701476024534, 0.44295589496084076)

In [66]:
scipy.stats.jarque_bera(hfi)

(25656.585999171326, 0.0)

In [73]:
erk.is_normal(hfi)

False

In [74]:
erk.is_normal(normal_rets)

True

In [75]:
hfi.aggregate(erk.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool

In [76]:
ffme = erk.get_ffme_returns()
erk.skewness(ffme)

SmallCap    4.410739
LargeCap    0.233445
dtype: float64

In [77]:
erk.kurtosis(ffme)

SmallCap    46.845008
LargeCap    10.694654
dtype: float64

In [80]:
ffme.aggregate(erk.is_normal)

SmallCap    False
LargeCap    False
dtype: bool